name: ETL Pipeline
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest src/tests/

      - name: Execute ETL
        run: |
          python src/extract.py > extracted.json
          python src/transform.py < extracted.json > transformed.json
          python src/load.py < transformed.json

      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: output.csv